# tests/integration/test_fate_pipeline.py
"""
Integration test for the full FATE genetic algorithm pipeline.

This test runs the complete Algorithm 1 loop — population initialisation,
fitness evaluation (K-fold cross-validation with AIF360 fairness metrics),
selection, crossover, mutation, and duplicate removal — on a small synthetic
dataset.  It is intentionally end-to-end: no component is mocked, so the test
catches integration failures that unit tests cannot (e.g., index mismatches
between the feature matrix and the original DataFrame passed to fairness_metrics,
or serialisation errors in the CSV cache).

The synthetic dataset is generated by ``sklearn.datasets.make_classification``
with a binary ``sex`` protected attribute added manually.  The GA is run with
a reduced configuration (2 generations, 4 individuals, LR classifier) to keep
total wall-clock time under ~60 seconds.
"""
import numpy as np
import pytest

VALID_TECHNIQUES = [
    'standard', 'stratified_sampling', 'oversampling', 'undersampling',
    'clustering', 'ipw', 'matching', 'min_max_scaling',
]


class TestFatePipelineIntegration:
    """End-to-end FATE pipeline tests on a synthetic binary classification dataset."""

    @pytest.fixture(autouse=True)
    def _load_modules_and_dataset(self, synthetic_fate_dataset):
        """
        Import modules inside the fixture so import errors are reported as test
        failures rather than collection errors, making diagnosis easier.
        """
        from preprocessing import prepare_data_model
        from genetic_algorithm import genetic_algorithm

        self.prepare_data_model = prepare_data_model
        self.genetic_algorithm = genetic_algorithm
        self.raw_df = synthetic_fate_dataset

    def test_pipeline_returns_a_tuple(self):
        """
        ``genetic_algorithm`` must return a non-None tuple.

        A None return value would indicate that the population was empty after
        the final generation or that an unhandled exception was swallowed.
        The return type is the contract between the GA and ``main.execute_fate``.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        result = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
            alpha=0.5, beta=0.5,
        )
        assert result is not None
        assert isinstance(result, tuple), f"Expected tuple, got {type(result)}"

    def test_pipeline_returns_five_fields(self):
        """
        The returned tuple must have exactly five fields:
        (techniques, model, fitness_value, fairness_score, performance_score).

        ``main.execute_fate`` accesses indices [0]–[4] without length-checking;
        a shorter tuple would cause silent None fields in the results CSV.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        result = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        assert len(result) == 5, (
            f"Expected 5-tuple (techniques, model, fitness, fairness, performance); "
            f"got {len(result)}-tuple: {result}"
        )

    def test_returned_techniques_are_nonempty_list(self):
        """
        The first field of the result must be a non-empty list of technique strings.

        An empty list means the GA converged to an individual with no preprocessing
        techniques, which is a valid but degenerate solution.  A non-list type
        (e.g., None) indicates that ``_select_parents`` produced an empty pool or
        that ``_unpack_fitness_result`` misidentified the tuple structure.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        techniques, *_ = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        assert isinstance(techniques, list), (
            f"Expected list of techniques; got {type(techniques)}"
        )
        assert len(techniques) > 0, "Best individual must contain at least one technique"

    def test_all_returned_techniques_are_valid(self):
        """
        Every technique in the best individual's chromosome must belong to the
        eight-element search space T defined in ``practices``.

        An out-of-vocabulary technique string would silently pass through
        ``apply_techniques`` as a no-op (the dispatch dict returns data unchanged),
        so this test catches mutation or crossover bugs that introduce invalid names.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        techniques, *_ = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        for t in techniques:
            assert t in VALID_TECHNIQUES, (
                f"Technique '{t}' is not in the valid search space T={VALID_TECHNIQUES}"
            )

    def test_returned_techniques_have_no_duplicates(self):
        """
        The best individual's chromosome must not contain repeated techniques.

        Duplicates waste gene slots and increase chromosome length without adding
        preprocessing steps (applying the same technique twice is a no-op for most
        transformations).  The ``_unique_preserve_order`` function is supposed to
        prevent this; a duplicate in the final result indicates it is not applied
        after mutation.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        techniques, *_ = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        assert len(techniques) == len(set(techniques)), (
            f"Best individual contains duplicate techniques: {techniques}"
        )

    def test_fitness_score_is_a_finite_float(self):
        """
        The fitness value in the result must be a finite float.

        ``float('inf')`` is the sentinel returned by ``fitness.fitness`` on
        catastrophic failure (empty target, all folds failed).  An infinite
        fitness in the best individual means every evaluated individual failed,
        which signals a dataset or classifier configuration problem rather than
        a genuine GA result.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        _, _, fitness_val, _, _ = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        assert isinstance(fitness_val, (int, float, np.floating)), (
            f"Fitness value must be numeric; got {type(fitness_val)}"
        )
        assert np.isfinite(fitness_val), (
            f"Fitness value must be finite; got {fitness_val}. "
            "This indicates all CV folds failed during fitness evaluation."
        )

    def test_fitness_score_is_in_plausible_range(self):
        """
        The fitness value must be in a plausible range for the default weight configuration.

        With perf_weight=0.5 and fair_weight=0.5:
          fitness = 0.5 × PS − 0.5 × FS
          PS ∈ [0, 1]  (PR-AUC), FS ∈ [0, ∞) but typically [0, 1] for |SPD+EOD+DI|/3
          Minimum plausible: 0.5 × 0 − 0.5 × 1 = −0.5
          Maximum plausible: 0.5 × 1 − 0.5 × 0 = +0.5

        Values outside [−2, 1] indicate an arithmetic error or a fairness score
        that is wildly out of the [0, 1] normalization range.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        _, _, fitness_val, _, _ = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        assert -2.0 <= fitness_val <= 1.0, (
            f"Fitness value {fitness_val} is outside the expected range [−2, 1]"
        )

    def test_model_field_echoes_input(self):
        """
        The model field in the result tuple must echo the model identifier passed in.

        ``main.execute_fate`` uses this field to populate the 'model_used' column
        in the results CSV; a mismatch would link results to the wrong classifier.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        _, model_used, *_ = self.genetic_algorithm(
            sample_ready, 'sex', 'target', 'lr',
            generations=2, population_size=4,
        )
        assert model_used == 'lr', (
            f"Expected model_used='lr'; got '{model_used}'"
        )

    def test_pipeline_raises_on_none_model(self):
        """
        Passing model=None must raise a ValueError immediately, not produce a
        silent infinity or a cryptic error deep in the sklearn call stack.

        The model identifier is the only required argument that is not part of
        the GA chromosome; a clear error prevents misleading 'all folds failed'
        logs when the root cause is simply a missing argument.
        """
        sample_ready = self.prepare_data_model(self.raw_df.copy(), 'target', 'sex')
        with pytest.raises(ValueError, match="model"):
            self.genetic_algorithm(
                sample_ready, 'sex', 'target', model=None,
                generations=1, population_size=2,
            )
